### ISSUE TITLE
Libre.fm scrobbling?

### ISSUE THREAD

**Issue by soredake** [hawx/mpd-scrobbler#4]

**Comment by hawx** [comment]
It looks like libre.fm uses the [old Last.fm API](http://www.last.fm/api/submissions) which I haven't implemented here, so it is not possible to support libre.fm. Though I'd be happy to accept a pull request.

**Comment by soredake** [comment]
Seems librefm supports 2.0 https://git.gnu.io/foocorp/librefm/wikis/Librefm_API_methods, or am I wrong?

**Comment by hawx** [comment]
It supports some but not the `track.scrobble` method that is used by mpd-scrobbler.
